### ISSUE TITLE
No definition of [libaria] for OS version [xenial]

### ISSUE THREAD

**Issue by amineHorseman** [amor-ros-pkg/rosaria#48]
Hello,

While trying to execute `rosdep install rosaria` on Ros Kinetic in Ubuntu 16.04 I got the following error:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosaria: No definition of [libaria] for OS version [xenial]

```

**Comment by reed-adept** [comment]
Responded here: http://answers.ros.org/question/235153/install-rosaria-from-source-in-ros-kinetic-kame/

I'll add entries to rosdep for Ubuntu wily and xenial but they are still going to refer to an old repackaging of ARIA 2.8.0 that someone made a while ago.  To get the current version someone should either update libaria.rdmanifest to work directly with the current version of the original ARIA package from robots.mobilerobots.com, or repackage the current version of ARIA similar to 2.8.0 and update libaria.rdmanifest.    I'm not going to be able to do this for every new version of ARIA and Ubuntu but if anyone else wants to do so go ahead.  Eventually I'll remove libaria from the rosaria dependencies (people will just have to install ARIA separately) unless someone wants to take over maintaining this aspect of rosaria.

**Comment by reed-adept** [comment]
My pull request to update rosdistro: https://github.com/ros/rosdistro/pull/11636

Not sure if this will solve the specific error or not yet... easiest solution is to install ARIA, then make rosaria.

**Comment by amineHorseman** [comment]
Thanks @reed-adept,

This solved the rosdep error.

But since it still referring the old repackaging of ARIA 2.8.0 and not the current version, I don't know if we should close the issue or let it open?

**Comment by reed-adept** [comment]
I think all or most documentation on how to get started with rosaria now just tells you to install ARIA directly since this is currently the only way to be using the most recent version of ARIA.  Someday libaria.rdmanifest should be reimplemented to deal with the ARIA tarball from mobilerobots.com (or the whole way ARIA is installed refactored to match LSB/Ubuntu/Debian filesystem layout standards and other requirements to get libaria into repositories that rosdep can pull from.)
